# Generated by Django 4.2.4 on 2023-10-09 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aviator2', '0002_profile_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='created',
        ),
    ]
