# Generated by Django 4.2.4 on 2023-10-09 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aviator2', '0004_alter_profile_options_profile_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='created',
            new_name='created_at',
        ),
    ]
